version: "3.8"
services:
  nginx:
    build: .
    container_name: nginx
    ports:
      - '80:80'
    # volumes:
    #   - ./dist:/var/www/html/dist
    #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    #   - ./nginx/.htpasswd:/etc/nginx/.htpasswd